DROP TABLE LOCATIONS;
DROP TABLE DEPARTMENTS;
DROP TABLE JOBS;
DROP TABLE EMPLOYEES;

CREATE TABLE LOCATIONS (
  LOCATION_ID INT(8) PRIMARY KEY,
  STREET_ADDRESS VARCHAR(40),
  POSTAL_CODE VARCHAR(12),
  CITY VARCHAR(30) NOT NULL,
  STATE_PROVINCE VARCHAR(25)
);

ALTER TABLE locations CHANGE location_id location_id INT(8) AUTO_INCREMENT;



CREATE TABLE DEPARTMENTS (
  DEPARTMENT_ID INT(8) PRIMARY KEY,
  DEPARTMENT_NAME VARCHAR(30) NOT NULL,
  LOCATION_ID INT(8)
);

ALTER TABLE departments CHANGE department_id department_id INT(8) AUTO_INCREMENT;



CREATE TABLE JOBS (
  JOB_ID INT(8) PRIMARY KEY,
  JOB_TITLE VARCHAR(35) NOT NULL,
  MIN_SALARY INT(8),
  MAX_SALARY INT(8)
);

ALTER TABLE jobs CHANGE job_id job_id INT(8) AUTO_INCREMENT;



CREATE TABLE EMPLOYEES (
  EMPLOYEE_ID INT(8) PRIMARY KEY,
  FIRST_NAME VARCHAR(20) NOT NULL,
  LAST_NAME VARCHAR(25) NOT NULL,
  EMAIL VARCHAR(25) NOT NULL,
  PHONE_NUMBER VARCHAR(20),
  HIRE_DATE DATE NOT NULL,
  JOB_ID INT(8) NOT NULL,
  SALARY DECIMAL(8, 2),
  COMMISSION_PCT DECIMAL(8, 2),
  MANAGER_ID INT(8),
  DEPARTMENT_ID INT(8)
);

ALTER TABLE employees CHANGE employee_id employee_id INT(8) AUTO_INCREMENT;



/* ----------------------- ADD Foreign Keys ----------------------- */

ALTER TABLE departments
  ADD FOREIGN KEY FK_DEPARTMENTS_LOCATIONS (location_id)
  REFERENCES locations(location_id);

ALTER TABLE employees
  ADD FOREIGN KEY FK_EMPLOYEES_DEPARTMENTS (department_id)
  REFERENCES departments(department_id);

ALTER TABLE employees
  ADD FOREIGN KEY FK_EMPLOYEES_JOBS (job_id)
  REFERENCES jobs(job_id);

ALTER TABLE employees
  ADD FOREIGN KEY FK_EMPLOYEES_MANAGER (manager_id)
  REFERENCES employees(employee_id);

/* --------------------- END ADD Foreign Keys --------------------- */