DROP TABLE LOCATIONS;
DROP TABLE DEPARTMENTS;
DROP TABLE JOBS;
DROP TABLE EMPLOYEES;


// ---------------------- CREATE TABLES ----------------------

CREATE TABLE LOCATIONS (
  LOCATION_ID     NUMBER PRIMARY KEY,
  STREET_ADDRESS  VARCHAR2(40),
  POSTAL_CODE     VARCHAR2(12),
  CITY            VARCHAR2(30) NOT NULL,
  STATE_PROVINCE  VARCHAR2(25)
);

CREATE TABLE DEPARTMENTS (
  DEPARTMENT_ID   NUMBER PRIMARY KEY,
  DEPARTMENT_NAME VARCHAR2(30) NOT NULL,
  LOCATION_ID     NUMBER
);

CREATE TABLE JOBS (
  JOB_ID      VARCHAR2(10) PRIMARY KEY,
  JOB_TITLE   VARCHAR2(35) NOT NULL,
  MIN_SALARY  NUMBER(6),
  MAX_SALARY  NUMBER(6)
);

CREATE TABLE EMPLOYEES (
  EMPLOYEE_ID     NUMBER PRIMARY KEY,
  FIRST_NAME      VARCHAR2(20) NOT NULL,
  LAST_NAME       VARCHAR2(25) NOT NULL,
  EMAIL           VARCHAR2(25) NOT NULL,
  PHONE_NUMBER    VARCHAR2(20),
  HIRE_DATE       DATE NOT NULL,
  JOB_ID          VARCHAR2(10) NOT NULL,
  SALARY          NUMBER(8, 2),
  COMMISSION_PCT  NUMBER(2, 2),
  MANAGER_ID      NUMBER,
  DEPARTMENT_ID   NUMBER
);

// -------------------- END CREATE TABLES --------------------



// ------------ CREATE SEQUENCES FOR PRIMARY KEYS ------------

CREATE SEQUENCE tab_departments_seq
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE tab_employees_seq
  START WITH 1
  INCREMENT BY 1;

CREATE SEQUENCE zth_seq
  START WITH 406
  INCREMENT BY 1;

// ---------- END CREATE SEQUENCES FOR PRIMARY KEYS ----------



// --------------------- ADD CONSTRAINTS ---------------------

ALTER TABLE departments
ADD CONSTRAINT FK_DEPARTMENTS_LOCATIONS
FOREIGN KEY (location_id) REFERENCES locations(location_id);

ALTER TABLE employees
ADD CONSTRAINT FK_EMPLOYEES_DEPARTMENTS
FOREIGN KEY  (department_id) REFERENCES departments(department_id);

ALTER TABLE employees
ADD CONSTRAINT FK_EMPLOYEES_JOBS
FOREIGN KEY (job_id) REFERENCES jobs(job_id);

ALTER TABLE employees
ADD CONSTRAINT FK_EMPLOYEES_MANAGER
FOREIGN KEY (manager_id) REFERENCES employees(employee_id);

// ------------------- END ADD CONSTRAINTS -------------------